name: MyApp

on:
  push:
    # branches:
    #   - main

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Run MyApp Backup
        uses: berkayy-atas/marketplace-test-workflow@latest
        with:
          activation_code: ${{ secrets.ACTIVATION_CODE }}
          encryption_key: ${{ secrets.ENCRYPTION_KEY }}
          use_org_id: true
